VERSION 0.6

ARG --required PATCHLEVEL
ARG UBUNTU_VERSION=22.04
ARG IMAGE_NAME=docker.allgeier-it.de:5000/julia36-ubuntu-test
ARG JUP_USER
ARG JUP_PASSWORD

julia:
        BUILD ./julia/+release --PATCHLEVEL=$PATCHLEVEL --IMAGE_NAME=$IMAGE_NAME --JUP_USER=$JUP_USER --JUP_PASSWORD=$JUP_PASSWORD

mailserver:
        BUILD ./mailserver/+release --PATCHLEVEL=latest

mongo:
        BUILD ./mongo/+release --PATCHLEVEL=latest

all:
        BUILD +mongo
        BUILD +mailserver
        BUILD +julia
